# Generated by Django 2.2.3 on 2019-07-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='reg',
        ),
    ]
